import streamlit as st
import google.generativeai as genai
import sqlite3
from datetime import datetime

# --- 1. CONFIG ---
API_KEY = "AIzaSyAb9w-J1f5e2TOZS9rK1PHtY0VVQ5kjLNg"
genai.configure(api_key=API_KEY, transport='rest')

# --- 2. DATABASE (Nayi Table suggestions ke saath) ---
def init_db():
    conn = sqlite3.connect('memories.db', check_same_thread=False)
    c = conn.cursor()
    c.execute('CREATE TABLE IF NOT EXISTS notes (content TEXT, date TEXT, suggestions TEXT)')
    conn.commit()
    return conn, c

conn, c = init_db()

# --- 3. VIP INTERFACE CSS ---
st.set_page_config(page_title="Gemini Voice AI Pro", layout="wide")

st.markdown("""
<style>
    .stApp { background: linear-gradient(135deg, #0f0c29, #302b63, #24243e); color: white; }
    h1 { color: #00d2ff; text-align: center; font-weight: bold; text-shadow: 2px 2px 10px #00d2ff; }
    .stButton>button { 
        background: linear-gradient(45deg, #00d2ff, #3a7bd5); 
        color: white; border-radius: 20px; border: none; height: 3em; font-weight: bold;
    }
    .stMarkdown { background: rgba(255, 255, 255, 0.1); padding: 20px; border-radius: 15px; border: 1px solid #00d2ff; }
</style>
""", unsafe_allow_html=True)

st.title("🎙️ Gemini Smart Voice Pro")
st.write("---")

# --- 4. MAIN UI ---
uploaded_file = st.file_uploader("Apni Audio file upload karein", type=['mp3', 'wav', 'm4a'])

if uploaded_file:
    st.audio(uploaded_file)
    if st.button("Analyze & Suggest 🚀"):
        with st.spinner("Gemini is thinking..."):
            try:
                model = genai.GenerativeModel('gemini-1.5-flash')
                audio_data = {"mime_type": uploaded_file.type, "data": uploaded_file.read()}
                
                # Smart Prompt
                prompt = "Summarize this audio in Urdu/English mix and give 3 smart suggestions based on the pattern of conversation."
                response = model.generate_content([prompt, audio_data])
                
                # Separate Result & Suggestions
                res_text = response.text
                st.subheader("📝 Analysis & Suggestions")
                st.markdown(res_text)
                
                # Save to DB
                c.execute("INSERT INTO notes VALUES (?, ?, ?)", 
                          (res_text, datetime.now().strftime("%Y-%m-%d %H:%M"), "Generated by Gemini"))
                conn.commit()
                st.balloons()
            except Exception as e:
                st.error(f"Error: {e}")

# --- 5. SIDEBAR HISTORY ---
st.sidebar.title("📜 Past Memories")
if st.sidebar.button("Show All"):
    res = c.execute("SELECT * FROM notes ORDER BY date DESC").fetchall()
    for r in res:
        with st.sidebar.expander(f"📅 {r[1]}"):
            st.write(r[0])

if st.sidebar.button("Clear All 🗑️"):
    c.execute("DELETE FROM notes")
    conn.commit()
    st.sidebar.success("Cleared!")